import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FaGithub, FaInstagram, FaLinkedin, FaTwitter } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed w-full bg-green-500 h-8 flex flex-row justify-center justify-evenly text-black p-2 z-10">
          <a href="https://www.linkedin.com/in/gauthamys"><FaLinkedin /></a>
          <a><FaGithub /></a>
          <a><FaInstagram /></a>
          <a><FaXTwitter /></a>
        </div>
        {children}
      </body>
    </html>
  );
}
